# Generated by Django 4.2.5 on 2023-11-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='crn',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='account',
            name='subject',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='account',
            name='term',
            field=models.CharField(default='', max_length=10),
        ),
    ]
