# Generated by Django 4.2.5 on 2023-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_crn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='subject',
            field=models.CharField(default='DefaultSubject', max_length=5),
        ),
        migrations.AlterField(
            model_name='account',
            name='term',
            field=models.CharField(default='DefaultTerm', max_length=10),
        ),
    ]
