# Generated by Django 4.2.5 on 2024-02-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_watchedclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='crn',
        ),
        migrations.RemoveField(
            model_name='account',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='account',
            name='term',
        ),
        migrations.AddField(
            model_name='watchedclass',
            name='subject',
            field=models.CharField(default='DefaultSubject', max_length=5),
        ),
        migrations.AlterField(
            model_name='watchedclass',
            name='title',
            field=models.CharField(default='DefaultTerm', max_length=100),
        ),
        migrations.AlterField(
            model_name='watchedclass',
            name='url',
            field=models.CharField(default='DefaultTerm', max_length=100),
        ),
    ]
