# Generated by Django 4.2.5 on 2024-02-21 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_account_crn_remove_account_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchedclass',
            name='subject',
        ),
    ]
