# Generated by Django 4.2.5 on 2024-02-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_watchedclass_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedclass',
            name='subject',
            field=models.CharField(default='DefaultSubject', max_length=5),
        ),
        migrations.AddField(
            model_name='watchedclass',
            name='term',
            field=models.CharField(default='DefaultTerm', max_length=10),
        ),
    ]
