# Generated by Django 4.2.5 on 2024-02-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_watchedclass_subject_watchedclass_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='crn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='subject',
            field=models.CharField(default='DefaultSubject', max_length=5),
        ),
        migrations.AddField(
            model_name='account',
            name='term',
            field=models.CharField(default='DefaultTerm', max_length=10),
        ),
    ]
