# Generated by Django 4.2.5 on 2024-02-21 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_account_crn_account_subject_account_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchedclass',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='watchedclass',
            name='term',
        ),
        migrations.AlterField(
            model_name='watchedclass',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='watchedclasses', to=settings.AUTH_USER_MODEL),
        ),
    ]
